// Keyword taxonomy from CLAUDE.md §3
// Each group has a weight and a list of terms (case-insensitive matching)

export interface KeywordGroup {
  name: string
  weight: number
  terms: string[]
}

export const KEYWORD_GROUPS: KeywordGroup[] = [
  {
    name: 'b2b_domain',
    weight: 5,
    terms: [
      'B2B',
      'enterprise',
      'developer tools',
      'SaaS',
      'agreement management',
      'contract management',
      'CRM',
      'customer platform',
      'go-to-market',
      'GTM',
      'contact center',
      'fintech',
      'financial services',
      'fraud',
      'risk',
      'dashboard',
      'admin tools',
      'data visualization',
      'reporting',
      'collaboration tools',
      'productivity tools',
      'API',
      'platform ecosystem',
      'workflow automation',
      'HR technology',
      'talent platform',
      'internal tools',
      'complex systems',
      'multi-product platform',
      'CMS',
    ],
  },
  {
    name: 'ai_emerging',
    weight: 4,
    terms: [
      'AI-powered',
      'AI-first',
      'agentic AI',
      'AI agents',
      'conversational UI',
      'voice',
      'LLM',
      'generative AI',
      'AI-assisted design',
      'probabilistic systems',
      'AI concierge',
      'digital twin',
      'RAG',
      'retrieval-augmented generation',
      'trust',
      'transparency',
      'human-in-the-loop',
      'AI design patterns',
      'reusable AI UX',
      'rapid prototyping with AI',
      'MCP',
    ],
  },
  {
    name: 'core_design',
    weight: 3,
    terms: [
      'product designer',
      'UX designer',
      'UX design',
      'interaction design',
      'visual design',
      'end-to-end design',
      'user flows',
      'wireframes',
      'prototyping',
      'design systems',
      'systems thinking',
      'information architecture',
      'pixel-perfect',
      'responsive',
      'cross-platform',
      'accessibility',
      'WCAG',
      'a11y',
      'content design',
      'UX writing',
      'motion design',
      'component-based',
      'design tokens',
    ],
  },
  {
    name: 'methods',
    weight: 2,
    terms: [
      'user research',
      'usability testing',
      'user-centered design',
      'design thinking',
      'journey mapping',
      'A/B testing',
      'experimentation',
      'Agile',
      'Scrum',
      'personas',
      'storyboards',
      'design critique',
      'metrics-driven',
      'funnel analysis',
      'conversion optimization',
      'conversion',
      'scalable design patterns',
      'cross-cloud',
      'multi-surface design',
      '0-to-1',
      'zero to one',
    ],
  },
  {
    name: 'soft_skills',
    weight: 2,
    terms: [
      'cross-functional collaboration',
      'cross-functional',
      'storytelling',
      'design rationale',
      'navigate ambiguity',
      'ambiguity',
      'stakeholder communication',
      'stakeholder alignment',
      'data-informed',
      'strategic product thinking',
      'strategic',
      'growth mindset',
      'continuous learning',
      'mentorship',
      'design culture',
      'balance user needs',
      'business goals',
    ],
  },
  {
    name: 'tools',
    weight: 1,
    terms: [
      'Figma',
      'Adobe Creative Cloud',
      'Framer',
      'Sketch',
      'HTML',
      'CSS',
      'JavaScript',
      'Miro',
      'Qualtrics',
      'Maze',
      'Google Analytics',
      'web analytics',
      'CMS',
      'Phenom',
      'Workday',
      'ServiceNow',
      'Airtable',
      'Jira',
      'Webflow',
      'Cursor',
      'Claude Code',
    ],
  },
]

// Flat list of all terms for quick lookup
export const ALL_TERMS = KEYWORD_GROUPS.flatMap((g) => g.terms)
