// One-off script: dedupes new ATS candidate lists against the existing
// poll-ats/companies.ts and prints ADDITIONS grouped by ATS. Paste the
// output into companies.ts.
//
// Usage: npx tsx scripts/merge-ats-candidates.ts

import { ATS_COMPANIES } from '../supabase/functions/poll-ats/companies'

type AtsType = 'greenhouse' | 'lever' | 'ashby' | 'smartrecruiters' | 'icims'
interface Candidate { name: string; ats: AtsType; slug: string }

// ── Greenhouse candidates from agent ─────────────────────────────────────────
const GREENHOUSE: Candidate[] = [
  { name: 'Allbirds', ats: 'greenhouse', slug: 'allbirds' },
  { name: 'Amwell', ats: 'greenhouse', slug: 'amwell' },
  { name: 'AppDirect', ats: 'greenhouse', slug: 'appdirect' },
  { name: 'Apptronik', ats: 'greenhouse', slug: 'apptronik' },
  { name: 'Astranis', ats: 'greenhouse', slug: 'astranis' },
  { name: 'Automattic', ats: 'greenhouse', slug: 'automatticcareers' },
  { name: 'Axon', ats: 'greenhouse', slug: 'axon' },
  { name: 'Axonius', ats: 'greenhouse', slug: 'axonius' },
  { name: 'Behavox', ats: 'greenhouse', slug: 'behavox' },
  { name: 'Benevity', ats: 'greenhouse', slug: 'benevity' },
  { name: 'BetterHelp', ats: 'greenhouse', slug: 'betterhelp' },
  { name: 'BigID', ats: 'greenhouse', slug: 'bigid' },
  { name: 'BitGo', ats: 'greenhouse', slug: 'bitgo' },
  { name: 'Block', ats: 'greenhouse', slug: 'block' },
  { name: 'Blockchain.com', ats: 'greenhouse', slug: 'blockchain' },
  { name: 'Bluecrew', ats: 'greenhouse', slug: 'bluecrewjobs' },
  { name: 'Branch', ats: 'greenhouse', slug: 'branch' },
  { name: 'Built In', ats: 'greenhouse', slug: 'builtin' },
  { name: 'Bungie', ats: 'greenhouse', slug: 'bungie' },
  { name: 'Cameo', ats: 'greenhouse', slug: 'cameo' },
  { name: 'Candid', ats: 'greenhouse', slug: 'candid' },
  { name: 'Canonical', ats: 'greenhouse', slug: 'canonical' },
  { name: 'Carvana', ats: 'greenhouse', slug: 'carvana' },
  { name: 'Celonis', ats: 'greenhouse', slug: 'celonis' },
  { name: 'CircleCI', ats: 'greenhouse', slug: 'circleci' },
  { name: 'CLEAR', ats: 'greenhouse', slug: 'clear' },
  { name: 'Clever', ats: 'greenhouse', slug: 'clever' },
  { name: 'CodePath', ats: 'greenhouse', slug: 'codepath' },
  { name: 'Consensys', ats: 'greenhouse', slug: 'consensys' },
  { name: 'Course Hero', ats: 'greenhouse', slug: 'coursehero' },
  { name: 'Cresta', ats: 'greenhouse', slug: 'cresta' },
  { name: 'DeepMind', ats: 'greenhouse', slug: 'deepmind' },
  { name: 'Earnin', ats: 'greenhouse', slug: 'earnin' },
  { name: 'Ecobee', ats: 'greenhouse', slug: 'ecobee' },
  { name: 'Eight Sleep', ats: 'greenhouse', slug: 'eightsleep' },
  { name: 'Everlane', ats: 'greenhouse', slug: 'everlane' },
  { name: 'FanDuel', ats: 'greenhouse', slug: 'fanduel' },
  { name: 'Fictiv', ats: 'greenhouse', slug: 'fictiv' },
  { name: 'Flipp', ats: 'greenhouse', slug: 'flipp' },
  { name: 'Formlabs', ats: 'greenhouse', slug: 'formlabs' },
  { name: 'FourKites', ats: 'greenhouse', slug: 'fourkites' },
  { name: 'FuboTV', ats: 'greenhouse', slug: 'fubotv' },
  { name: 'General Assembly', ats: 'greenhouse', slug: 'general' },
  { name: 'Genius Sports', ats: 'greenhouse', slug: 'geniussports' },
  { name: 'GetYourGuide', ats: 'greenhouse', slug: 'getyourguide' },
  { name: 'Ghost', ats: 'greenhouse', slug: 'ghost' },
  { name: 'Glassdoor', ats: 'greenhouse', slug: 'glassdoor' },
  { name: 'GoCardless', ats: 'greenhouse', slug: 'gocardless' },
  { name: 'GoDaddy', ats: 'greenhouse', slug: 'godaddy' },
  { name: 'GoFundMe', ats: 'greenhouse', slug: 'gofundme' },
  { name: 'Grailed', ats: 'greenhouse', slug: 'grailed' },
  { name: 'Graphcore', ats: 'greenhouse', slug: 'graphcore' },
  { name: 'HackerRank', ats: 'greenhouse', slug: 'hackerrank' },
  { name: 'HiveMQ', ats: 'greenhouse', slug: 'hivemq' },
  { name: 'Housecall Pro', ats: 'greenhouse', slug: 'housecall' },
  { name: 'Hudl', ats: 'greenhouse', slug: 'hudl' },
  { name: 'Huge', ats: 'greenhouse', slug: 'hugeinc' },
  { name: 'IEX', ats: 'greenhouse', slug: 'iex' },
  { name: 'Imply', ats: 'greenhouse', slug: 'imply' },
  { name: 'Indigo Ag', ats: 'greenhouse', slug: 'indigo' },
  { name: 'Instabase', ats: 'greenhouse', slug: 'instabase' },
  { name: 'Jamf', ats: 'greenhouse', slug: 'jamf' },
  { name: 'JetBrains', ats: 'greenhouse', slug: 'jetbrains' },
  { name: 'JFrog', ats: 'greenhouse', slug: 'jfrog' },
  { name: 'Jumio', ats: 'greenhouse', slug: 'jumio' },
  { name: 'JustAnswer', ats: 'greenhouse', slug: 'justanswer' },
  { name: 'Kargo', ats: 'greenhouse', slug: 'kargo' },
  { name: 'Kasisto', ats: 'greenhouse', slug: 'kasisto' },
  { name: 'Kickstarter', ats: 'greenhouse', slug: 'kickstarter' },
  { name: 'KnowBe4', ats: 'greenhouse', slug: 'knowbe4' },
  { name: 'Magic Leap', ats: 'greenhouse', slug: 'magicleap' },
  { name: 'MaintainX', ats: 'greenhouse', slug: 'maintainx' },
  { name: 'Make', ats: 'greenhouse', slug: 'make' },
  { name: 'Material Bank', ats: 'greenhouse', slug: 'materialbank' },
  { name: 'Mercari', ats: 'greenhouse', slug: 'mercari' },
  { name: 'Mirakl', ats: 'greenhouse', slug: 'mirakl' },
  { name: 'Mitratech', ats: 'greenhouse', slug: 'mitratech' },
  { name: 'Mozilla', ats: 'greenhouse', slug: 'mozilla' },
  { name: 'Nextdoor', ats: 'greenhouse', slug: 'nextdoor' },
  { name: 'Observe.AI', ats: 'greenhouse', slug: 'observeai' },
  { name: 'OpenTable', ats: 'greenhouse', slug: 'opentable' },
  { name: 'OpenWeb', ats: 'greenhouse', slug: 'openweb' },
  { name: 'Oportun', ats: 'greenhouse', slug: 'oportun' },
  { name: 'Optimove', ats: 'greenhouse', slug: 'optimove' },
  { name: 'Orchard', ats: 'greenhouse', slug: 'orchard' },
  { name: 'Pantheon', ats: 'greenhouse', slug: 'pantheon' },
  { name: 'Peloton', ats: 'greenhouse', slug: 'peloton' },
  { name: 'Plume', ats: 'greenhouse', slug: 'plume' },
  { name: 'Poshmark', ats: 'greenhouse', slug: 'poshmark' },
  { name: 'Public', ats: 'greenhouse', slug: 'public' },
  { name: 'Qualtrics', ats: 'greenhouse', slug: 'qualtrics' },
  { name: 'Radar', ats: 'greenhouse', slug: 'radar' },
  { name: 'RapidSOS', ats: 'greenhouse', slug: 'rapidsos' },
  { name: 'Remote', ats: 'greenhouse', slug: 'remotecom' },
  { name: 'ResortPass', ats: 'greenhouse', slug: 'resortpass' },
  { name: 'Ridgeline', ats: 'greenhouse', slug: 'ridgeline' },
  { name: 'Roblox', ats: 'greenhouse', slug: 'roblox' },
  { name: 'Roku', ats: 'greenhouse', slug: 'roku' },
  { name: 'Rubrik', ats: 'greenhouse', slug: 'rubrik' },
  { name: 'Scopely', ats: 'greenhouse', slug: 'scopely' },
  { name: 'Sezzle', ats: 'greenhouse', slug: 'sezzle' },
  { name: 'ShipMonk', ats: 'greenhouse', slug: 'shipmonk' },
  { name: 'Shopmonkey', ats: 'greenhouse', slug: 'shopmonkey' },
  { name: 'Sisense', ats: 'greenhouse', slug: 'sisense' },
  { name: 'Smartling', ats: 'greenhouse', slug: 'smartling' },
  { name: 'Smartsheet', ats: 'greenhouse', slug: 'smartsheet' },
  { name: 'Snackpass', ats: 'greenhouse', slug: 'snackpass' },
  { name: 'SoFi', ats: 'greenhouse', slug: 'sofi' },
  { name: 'SpaceX', ats: 'greenhouse', slug: 'spacex' },
  { name: 'Speechmatics', ats: 'greenhouse', slug: 'speechmatics' },
  { name: 'Splice', ats: 'greenhouse', slug: 'splice' },
  { name: 'StackBlitz', ats: 'greenhouse', slug: 'stackblitz' },
  { name: 'Stensul', ats: 'greenhouse', slug: 'stensul' },
  { name: 'Stitch Fix', ats: 'greenhouse', slug: 'stitch' },
  { name: 'StockX', ats: 'greenhouse', slug: 'stockx' },
  { name: 'Storyblocks', ats: 'greenhouse', slug: 'storyblocks' },
  { name: 'Sweetgreen', ats: 'greenhouse', slug: 'sweetgreen' },
  { name: 'Taboola', ats: 'greenhouse', slug: 'taboola' },
  { name: 'Talkspace', ats: 'greenhouse', slug: 'talkspace' },
  { name: 'Tanium', ats: 'greenhouse', slug: 'tanium' },
  { name: 'TaskRabbit', ats: 'greenhouse', slug: 'taskrabbit' },
  { name: 'Testlio', ats: 'greenhouse', slug: 'testlio' },
  { name: 'Textio', ats: 'greenhouse', slug: 'textio' },
  { name: 'Thinkific', ats: 'greenhouse', slug: 'thinkific' },
  { name: 'ThoughtExchange', ats: 'greenhouse', slug: 'thoughtexchange' },
  { name: 'ThoughtWorks', ats: 'greenhouse', slug: 'thoughtworks' },
  { name: 'ThousandEyes', ats: 'greenhouse', slug: 'thousandeyes' },
  { name: 'TouchBistro', ats: 'greenhouse', slug: 'touchbistro' },
  { name: 'Trailer Park', ats: 'greenhouse', slug: 'trailerpark' },
  { name: 'TripActions', ats: 'greenhouse', slug: 'tripactions' },
  { name: 'Trumid', ats: 'greenhouse', slug: 'trumid' },
  { name: 'Truveta', ats: 'greenhouse', slug: 'truveta' },
  { name: 'Tucows', ats: 'greenhouse', slug: 'tucows' },
  { name: 'Turing', ats: 'greenhouse', slug: 'turing' },
  { name: 'Twitch', ats: 'greenhouse', slug: 'twitch' },
  { name: 'Typeform', ats: 'greenhouse', slug: 'typeform' },
  { name: 'Uber Freight', ats: 'greenhouse', slug: 'uberfreight' },
  { name: 'Udemy', ats: 'greenhouse', slug: 'udemy' },
  { name: 'Updater', ats: 'greenhouse', slug: 'updater' },
  { name: 'Upstart', ats: 'greenhouse', slug: 'upstart' },
  { name: 'Upwork', ats: 'greenhouse', slug: 'upwork' },
  { name: 'Vercel', ats: 'greenhouse', slug: 'vercel' },
  { name: 'Veriff', ats: 'greenhouse', slug: 'veriff' },
  { name: 'Vox Media', ats: 'greenhouse', slug: 'voxmedia' },
  { name: 'Warp', ats: 'greenhouse', slug: 'warp' },
  { name: 'Waymo', ats: 'greenhouse', slug: 'waymo' },
  { name: 'Wheelhouse', ats: 'greenhouse', slug: 'wheelhouse' },
  { name: 'Wikimedia', ats: 'greenhouse', slug: 'wikimedia' },
  { name: 'Wunderkind', ats: 'greenhouse', slug: 'wunderkind' },
  { name: 'Xometry', ats: 'greenhouse', slug: 'xometry' },
  { name: 'Yext', ats: 'greenhouse', slug: 'yext' },
  { name: 'Yubico', ats: 'greenhouse', slug: 'yubico' },
  { name: 'ZipRecruiter', ats: 'greenhouse', slug: 'ziprecruiter' },
  { name: 'Zola', ats: 'greenhouse', slug: 'zola' },
]

// ── Ashby candidates from agent (393 verified) ───────────────────────────────
const ASHBY: Candidate[] = [
  { name: '0x', ats: 'ashby', slug: '0x' },
  { name: '10x Team', ats: 'ashby', slug: '10xteam' },
  { name: '9fin', ats: 'ashby', slug: '9fin' },
  { name: 'Abridge', ats: 'ashby', slug: 'Abridge' },
  { name: 'Aclima', ats: 'ashby', slug: 'aclima' },
  { name: 'Adaptive Security', ats: 'ashby', slug: 'adaptivesecurity' },
  { name: 'Addi', ats: 'ashby', slug: 'addi' },
  { name: 'AeroVect', ats: 'ashby', slug: 'aerovect' },
  { name: 'Aetherflux', ats: 'ashby', slug: 'aetherflux' },
  { name: 'Aghanim', ats: 'ashby', slug: 'aghanim' },
  { name: 'Aim4Hire', ats: 'ashby', slug: 'aim4hire' },
  { name: 'Aios Medical', ats: 'ashby', slug: 'Aios' },
  { name: 'Air Apps', ats: 'ashby', slug: 'airapps' },
  { name: 'AirOps', ats: 'ashby', slug: 'airops' },
  { name: 'Airwallex', ats: 'ashby', slug: 'airwallex' },
  { name: 'Aiwyn', ats: 'ashby', slug: 'aiwyn' },
  { name: 'Alan', ats: 'ashby', slug: 'alan' },
  { name: 'Alex AI', ats: 'ashby', slug: 'alexai' },
  { name: 'algo1', ats: 'ashby', slug: 'algo1' },
  { name: 'Allium', ats: 'ashby', slug: 'allium' },
  { name: 'Altura', ats: 'ashby', slug: 'altura' },
  { name: 'Ambience Healthcare', ats: 'ashby', slug: 'ambiencehealthcare' },
  { name: 'Ambient.ai', ats: 'ashby', slug: 'ambient.ai' },
  { name: 'American Housing', ats: 'ashby', slug: 'american-housing' },
  { name: 'Antai Ventures', ats: 'ashby', slug: 'antaiventures' },
  { name: 'Anyscale', ats: 'ashby', slug: 'anyscale' },
  { name: 'Applied Labs', ats: 'ashby', slug: 'appliedlabs' },
  { name: 'Aptura', ats: 'ashby', slug: 'aptura' },
  { name: 'ARQ', ats: 'ashby', slug: 'arq' },
  { name: 'Artisan', ats: 'ashby', slug: 'artisan' },
  { name: 'Assembled', ats: 'ashby', slug: 'assembledhq' },
  { name: 'Assembly', ats: 'ashby', slug: 'assembly' },
  { name: 'Astronomer', ats: 'ashby', slug: 'astronomer' },
  { name: 'Atticus', ats: 'ashby', slug: 'atticus' },
  { name: 'Attio', ats: 'ashby', slug: 'attio' },
  { name: 'August', ats: 'ashby', slug: 'august' },
  { name: 'Aurora Solar', ats: 'ashby', slug: 'aurorasolar' },
  { name: 'Away', ats: 'ashby', slug: 'away' },
  { name: 'Axiom Bio', ats: 'ashby', slug: 'axiombio' },
  { name: 'Axion', ats: 'ashby', slug: 'axion' },
  { name: 'Baseten', ats: 'ashby', slug: 'baseten' },
  { name: 'Basis AI', ats: 'ashby', slug: 'basis-ai' },
  { name: 'Beam Impact', ats: 'ashby', slug: 'beamimpact' },
  { name: 'Bedrock Robotics', ats: 'ashby', slug: 'bedrock-robotics' },
  { name: 'Bestow', ats: 'ashby', slug: 'bestow' },
  { name: 'Better Mortgage', ats: 'ashby', slug: 'better-mortgage' },
  { name: 'Binance.US', ats: 'ashby', slug: 'binance.us' },
  { name: 'BIO Protocol', ats: 'ashby', slug: 'bio' },
  { name: 'Bitstack', ats: 'ashby', slug: 'bitstack' },
  { name: 'Bjak', ats: 'ashby', slug: 'bjakcareer' },
  { name: 'Black Semiconductor', ats: 'ashby', slug: 'blacksemiconductor' },
  { name: 'Bland', ats: 'ashby', slug: 'bland' },
  { name: 'Brain Co.', ats: 'ashby', slug: 'brainco' },
  { name: 'Braintrust', ats: 'ashby', slug: 'braintrust' },
  { name: 'BRM', ats: 'ashby', slug: 'brm.ai' },
  { name: 'Bubble', ats: 'ashby', slug: 'bubble' },
  { name: 'Built Robotics', ats: 'ashby', slug: 'built-robotics' },
  { name: 'bunch', ats: 'ashby', slug: 'bunch' },
  { name: 'ButterflyMX', ats: 'ashby', slug: 'butterflymx' },
  { name: 'Candid Health', ats: 'ashby', slug: 'candidhealth' },
  { name: 'Cape', ats: 'ashby', slug: 'cape' },
  { name: 'Cartesia', ats: 'ashby', slug: 'cartesia' },
  { name: 'Causaly', ats: 'ashby', slug: 'causaly' },
  { name: 'Cellular Intelligence', ats: 'ashby', slug: 'cellular-intelligence' },
  { name: 'Chai Discovery', ats: 'ashby', slug: 'chaidiscovery' },
  { name: 'Character.AI', ats: 'ashby', slug: 'character' },
  { name: 'Clay Labs', ats: 'ashby', slug: 'claylabs' },
  { name: 'Clerk', ats: 'ashby', slug: 'Clerk' },
  { name: 'Clipboard', ats: 'ashby', slug: 'clipboard' },
  { name: 'Close', ats: 'ashby', slug: 'close' },
  { name: 'Cluely', ats: 'ashby', slug: 'cluely' },
  { name: 'CodeRabbit', ats: 'ashby', slug: 'coderabbit' },
  { name: 'Cognition', ats: 'ashby', slug: 'cognition' },
  { name: 'Comfy Org', ats: 'ashby', slug: 'comfy-org' },
  { name: 'Comulate', ats: 'ashby', slug: 'comulate' },
  { name: 'Conduit', ats: 'ashby', slug: 'Conduit' },
  { name: 'Conversion', ats: 'ashby', slug: 'conversion' },
  { name: 'Convex', ats: 'ashby', slug: 'convex-dev' },
  { name: 'Coreflow', ats: 'ashby', slug: 'coreflow' },
  { name: 'Credo.AI', ats: 'ashby', slug: 'credo.ai' },
  { name: 'Cursor', ats: 'ashby', slug: 'cursor' },
  { name: 'Dandy', ats: 'ashby', slug: 'dandy' },
  { name: 'DataGuard', ats: 'ashby', slug: 'dataguard' },
  { name: 'David AI', ats: 'ashby', slug: 'david-ai' },
  { name: 'Daydream', ats: 'ashby', slug: 'daydream-ai' },
  { name: 'Decagon', ats: 'ashby', slug: 'decagon' },
  { name: 'Deepgram', ats: 'ashby', slug: 'Deepgram' },
  { name: 'Deliveroo', ats: 'ashby', slug: 'deliveroo' },
  { name: 'Demandbase', ats: 'ashby', slug: 'demandbase' },
  { name: 'Distyl', ats: 'ashby', slug: 'Distyl' },
  { name: 'Docker', ats: 'ashby', slug: 'docker' },
  { name: 'Doss', ats: 'ashby', slug: 'doss' },
  { name: 'Duet', ats: 'ashby', slug: 'duet' },
  { name: 'Duna', ats: 'ashby', slug: 'duna' },
  { name: 'Dune', ats: 'ashby', slug: 'dune' },
  { name: 'Dust', ats: 'ashby', slug: 'dust' },
  { name: 'E2B', ats: 'ashby', slug: 'e2b' },
  { name: 'Ekho', ats: 'ashby', slug: 'ekho' },
  { name: 'ElevenLabs', ats: 'ashby', slug: 'elevenlabs' },
  { name: 'EliseAI', ats: 'ashby', slug: 'EliseAI' },
  { name: 'Elliptic', ats: 'ashby', slug: 'elliptic' },
  { name: 'Ema', ats: 'ashby', slug: 'ema' },
  { name: 'Embedding VC', ats: 'ashby', slug: 'embedding-vc' },
  { name: 'Equip Health', ats: 'ashby', slug: 'equip' },
  { name: 'Etched', ats: 'ashby', slug: 'Etched' },
  { name: 'Fable Security', ats: 'ashby', slug: 'fable' },
  { name: 'Fastino', ats: 'ashby', slug: 'fastino-ai' },
  { name: 'Fieldguide', ats: 'ashby', slug: 'fieldguide' },
  { name: 'Firecrawl', ats: 'ashby', slug: 'firecrawl' },
  { name: 'First Round Capital', ats: 'ashby', slug: 'firstround' },
  { name: 'Flashbots', ats: 'ashby', slug: 'flashbots.net' },
  { name: 'Flock Safety', ats: 'ashby', slug: 'Flock Safety' },
  { name: 'Flow Engineering', ats: 'ashby', slug: 'flowengineering' },
  { name: 'Fluidstack', ats: 'ashby', slug: 'fluidstack' },
  { name: 'Form Energy', ats: 'ashby', slug: 'formenergy' },
  { name: 'Formal', ats: 'ashby', slug: 'formal' },
  { name: 'Foundation', ats: 'ashby', slug: 'foundation' },
  { name: 'Foundry for Good', ats: 'ashby', slug: 'foundry-for-good' },
  { name: 'Foundry Robotics', ats: 'ashby', slug: 'foundry-robotics' },
  { name: 'FurtherAI', ats: 'ashby', slug: 'furtherai' },
  { name: 'Fyxer', ats: 'ashby', slug: 'fyxer' },
  { name: 'G2', ats: 'ashby', slug: 'g2' },
  { name: 'G2i', ats: 'ashby', slug: 'g2i' },
  { name: 'GameChanger', ats: 'ashby', slug: 'gamechanger' },
  { name: 'Garage', ats: 'ashby', slug: 'garage' },
  { name: 'Gecko Robotics', ats: 'ashby', slug: 'gecko-robotics' },
  { name: 'General Intelligence Company', ats: 'ashby', slug: 'generalintelligencecompany' },
  { name: 'GigaML', ats: 'ashby', slug: 'gigaml' },
  { name: 'Glacis AI', ats: 'ashby', slug: 'glacis-ai' },
  { name: 'Granola', ats: 'ashby', slug: 'granola' },
  { name: 'Gravity Climate', ats: 'ashby', slug: 'GravityClimate' },
  { name: 'GrowthX AI', ats: 'ashby', slug: 'GrowthX AI' },
  { name: 'Haast', ats: 'ashby', slug: 'haast' },
  { name: 'HackerOne', ats: 'ashby', slug: 'hackerone' },
  { name: 'Hadrian Automation', ats: 'ashby', slug: 'hadrian-automation' },
  { name: 'Handshake', ats: 'ashby', slug: 'handshake' },
  { name: 'HappyRobot', ats: 'ashby', slug: 'happyrobot.ai' },
  { name: 'Healthtech-1', ats: 'ashby', slug: 'Healthtech-1' },
  { name: 'Hedra', ats: 'ashby', slug: 'hedra' },
  { name: 'Helion', ats: 'ashby', slug: 'helion' },
  { name: 'Heron Power', ats: 'ashby', slug: 'heron-power' },
  { name: 'Hexa', ats: 'ashby', slug: 'hexa' },
  { name: 'Higgsfield AI', ats: 'ashby', slug: 'higgsfieldai' },
  { name: 'Hightouch', ats: 'ashby', slug: 'hightouch' },
  { name: 'Hippocratic AI', ats: 'ashby', slug: 'Hippocratic AI' },
  { name: 'Hopper', ats: 'ashby', slug: 'hopper' },
  { name: 'Horizon3 AI', ats: 'ashby', slug: 'horizon3ai' },
  { name: 'HUD', ats: 'ashby', slug: 'hud' },
  { name: 'Iambic Therapeutics', ats: 'ashby', slug: 'iambic-therapeutics' },
  { name: 'Ideogram', ats: 'ashby', slug: 'ideogram' },
  { name: 'Immersive Labs', ats: 'ashby', slug: 'immersivelabs' },
  { name: 'Inception Point AI', ats: 'ashby', slug: 'Inception Point AI' },
  { name: 'incident.io', ats: 'ashby', slug: 'incident' },
  { name: 'Inference', ats: 'ashby', slug: 'inference' },
  { name: 'Infinity Constellation', ats: 'ashby', slug: 'infinity-constellation' },
  { name: 'Inngest', ats: 'ashby', slug: 'inngest' },
  { name: 'insitro', ats: 'ashby', slug: 'insitro' },
  { name: 'Intangible', ats: 'ashby', slug: 'intangible.ai' },
  { name: 'Ivo', ats: 'ashby', slug: 'ivo-ai-inc' },
  { name: 'January', ats: 'ashby', slug: 'january' },
  { name: 'Jasper AI', ats: 'ashby', slug: 'Jasper AI' },
  { name: 'Jerry.ai', ats: 'ashby', slug: 'Jerry.ai' },
  { name: 'Jump', ats: 'ashby', slug: 'jump-app' },
  { name: 'Juniper Square', ats: 'ashby', slug: 'junipersquare' },
  { name: 'Kittl', ats: 'ashby', slug: 'kittl' },
  { name: 'Klarity', ats: 'ashby', slug: 'klarity-ai' },
  { name: 'Klue', ats: 'ashby', slug: 'klue' },
  { name: 'KOHO', ats: 'ashby', slug: 'koho' },
  { name: 'Kraken.com', ats: 'ashby', slug: 'kraken.com' },
  { name: 'Kubera Health', ats: 'ashby', slug: 'kubera-health' },
  { name: 'Kustomer', ats: 'ashby', slug: 'Kustomer' },
  { name: 'Lakera', ats: 'ashby', slug: 'lakera.ai' },
  { name: 'Lambda', ats: 'ashby', slug: 'lambda' },
  { name: 'LanceDB', ats: 'ashby', slug: 'lancedb' },
  { name: 'LangChain', ats: 'ashby', slug: 'langchain' },
  { name: 'Langfuse', ats: 'ashby', slug: 'langfuse' },
  { name: 'Laurel', ats: 'ashby', slug: 'laurel' },
  { name: 'Lavendo', ats: 'ashby', slug: 'lavendo' },
  { name: 'Lean TECHniques', ats: 'ashby', slug: 'leantechniques' },
  { name: 'Legion Health', ats: 'ashby', slug: 'legionhealth' },
  { name: 'Leland', ats: 'ashby', slug: 'leland' },
  { name: 'Levels.fyi', ats: 'ashby', slug: 'demo.levels.fyi' },
  { name: 'Linear', ats: 'ashby', slug: 'Linear' },
  { name: 'Liquid AI', ats: 'ashby', slug: 'liquid-ai' },
  { name: 'LiveKit', ats: 'ashby', slug: 'livekit' },
  { name: 'LlamaIndex', ats: 'ashby', slug: 'llamaindex' },
  { name: 'M13', ats: 'ashby', slug: 'm13' },
  { name: 'Magic AI', ats: 'ashby', slug: 'magic.dev' },
  { name: 'Matter Intelligence', ats: 'ashby', slug: 'matter-intelligence' },
  { name: 'Maxima', ats: 'ashby', slug: 'Maxima' },
  { name: 'Mem', ats: 'ashby', slug: 'mem.ai' },
  { name: 'Mercor', ats: 'ashby', slug: 'mercor' },
  { name: 'Metamorphic', ats: 'ashby', slug: 'metamorphic' },
  { name: 'Metaview', ats: 'ashby', slug: 'metaview' },
  { name: 'MightyBot', ats: 'ashby', slug: 'mightybot' },
  { name: 'Mintlify', ats: 'ashby', slug: 'Mintlify' },
  { name: 'Mirendil', ats: 'ashby', slug: 'mirendil' },
  { name: 'Modal', ats: 'ashby', slug: 'modal' },
  { name: 'Modus', ats: 'ashby', slug: 'modus' },
  { name: 'Momentic', ats: 'ashby', slug: 'momentic' },
  { name: 'MOXFIVE', ats: 'ashby', slug: 'moxfive' },
  { name: 'MUI', ats: 'ashby', slug: 'MUI' },
  { name: 'Multiverse', ats: 'ashby', slug: 'multiverse' },
  { name: 'Mural', ats: 'ashby', slug: 'mural' },
  { name: 'n8n', ats: 'ashby', slug: 'n8n' },
  { name: 'Nace AI', ats: 'ashby', slug: 'nace.ai' },
  { name: 'NetGear', ats: 'ashby', slug: 'netgear' },
  { name: 'Nirvana Insurance', ats: 'ashby', slug: 'nirvana' },
  { name: 'Nooks', ats: 'ashby', slug: 'nooks' },
  { name: 'Normal Computing', ats: 'ashby', slug: 'NormalComputing' },
  { name: 'Northwood Space', ats: 'ashby', slug: 'NorthwoodSpace' },
  { name: 'Notable', ats: 'ashby', slug: 'notable' },
  { name: 'Notion', ats: 'ashby', slug: 'notion' },
  { name: 'Nova Intelligence', ats: 'ashby', slug: 'novaintelligence' },
  { name: 'Numeric', ats: 'ashby', slug: 'numeric' },
  { name: 'Onebrief', ats: 'ashby', slug: 'onebrief' },
  { name: 'OnHires', ats: 'ashby', slug: 'onhires' },
  { name: 'OP Labs', ats: 'ashby', slug: 'oplabs' },
  { name: 'OpenArt', ats: 'ashby', slug: 'openart' },
  { name: 'OpusClip', ats: 'ashby', slug: 'opusclip' },
  { name: 'Orbital', ats: 'ashby', slug: 'orbital' },
  { name: 'Orum', ats: 'ashby', slug: 'orum' },
  { name: 'OurRitual', ats: 'ashby', slug: 'ourritual' },
  { name: 'Oyster', ats: 'ashby', slug: 'oyster' },
  { name: 'P2P.org', ats: 'ashby', slug: 'p2p.org' },
  { name: 'Parabola', ats: 'ashby', slug: 'parabola-io' },
  { name: 'Paradigm', ats: 'ashby', slug: 'paradigmai' },
  { name: 'Parallel Bio', ats: 'ashby', slug: 'parallel-bio' },
  { name: 'Parker Group', ats: 'ashby', slug: 'parker' },
  { name: 'Patreon', ats: 'ashby', slug: 'patreon' },
  { name: 'Pearl Health', ats: 'ashby', slug: 'pearlhealth' },
  { name: 'Pebl', ats: 'ashby', slug: 'pebl' },
  { name: 'Peec AI', ats: 'ashby', slug: 'Peec' },
  { name: 'Pennylane', ats: 'ashby', slug: 'pennylane' },
  { name: 'Percepta', ats: 'ashby', slug: 'percepta' },
  { name: 'Perchwell', ats: 'ashby', slug: 'Perchwell' },
  { name: 'Pergolux', ats: 'ashby', slug: 'pergolux' },
  { name: 'Persona', ats: 'ashby', slug: 'persona' },
  { name: 'Persona AI', ats: 'ashby', slug: 'persona.ai' },
  { name: 'Phantom', ats: 'ashby', slug: 'phantom' },
  { name: 'Physical Intelligence', ats: 'ashby', slug: 'physicalintelligence' },
  { name: 'Pika', ats: 'ashby', slug: 'pika' },
  { name: 'Pinecone', ats: 'ashby', slug: 'pinecone' },
  { name: 'Plain', ats: 'ashby', slug: 'plain' },
  { name: 'Plaud', ats: 'ashby', slug: 'Plaud' },
  { name: 'Playlab', ats: 'ashby', slug: 'Playlab' },
  { name: 'Polymarket', ats: 'ashby', slug: 'polymarket' },
  { name: 'Poolside', ats: 'ashby', slug: 'poolside' },
  { name: 'PostHog', ats: 'ashby', slug: 'posthog' },
  { name: 'Praxipal', ats: 'ashby', slug: 'praxipal' },
  { name: 'Prefect', ats: 'ashby', slug: 'prefect' },
  { name: 'Prelude', ats: 'ashby', slug: 'prelude' },
  { name: 'Prime Intellect', ats: 'ashby', slug: 'PrimeIntellect' },
  { name: 'Prior Labs', ats: 'ashby', slug: 'prior-labs' },
  { name: 'Prosper AI', ats: 'ashby', slug: 'prosper-ai' },
  { name: 'Puzzle.io', ats: 'ashby', slug: 'puzzle.io' },
  { name: 'Pylon', ats: 'ashby', slug: 'pylon-labs' },
  { name: 'Quora', ats: 'ashby', slug: 'quora' },
  { name: 'Radiant Industries', ats: 'ashby', slug: 'radiant-industries' },
  { name: 'Railway', ats: 'ashby', slug: 'railway' },
  { name: 'Rain', ats: 'ashby', slug: 'rain' },
  { name: 'Raycast', ats: 'ashby', slug: 'raycast' },
  { name: 'Raylu AI', ats: 'ashby', slug: 'raylu-ai' },
  { name: 'Recall', ats: 'ashby', slug: 'Recall' },
  { name: 'Recraft', ats: 'ashby', slug: 'recraft' },
  { name: 'Reducto', ats: 'ashby', slug: 'reducto' },
  { name: 'Reflection AI', ats: 'ashby', slug: 'reflectionai' },
  { name: 'Relevance AI', ats: 'ashby', slug: 'relevanceai' },
  { name: 'Render', ats: 'ashby', slug: 'render' },
  { name: 'Rerun', ats: 'ashby', slug: 'rerun' },
  { name: 'Resend', ats: 'ashby', slug: 'resend' },
  { name: 'Rev', ats: 'ashby', slug: 'rev' },
  { name: 'Revenue Vessel', ats: 'ashby', slug: 'RevenueVessel' },
  { name: 'RevenueBase', ats: 'ashby', slug: 'revenuebase-inc' },
  { name: 'RevenueCat', ats: 'ashby', slug: 'revenuecat' },
  { name: 'Rilla', ats: 'ashby', slug: 'rilla' },
  { name: 'Roadrunner', ats: 'ashby', slug: 'Roadrunner' },
  { name: 'RobCo', ats: 'ashby', slug: 'robco' },
  { name: 'Rollstack', ats: 'ashby', slug: 'rollstack' },
  { name: 'Rox Data', ats: 'ashby', slug: 'Rox-Data-Corp' },
  { name: 'Rutter', ats: 'ashby', slug: 'rutter' },
  { name: 'Sahara', ats: 'ashby', slug: 'Sahara' },
  { name: 'Salient', ats: 'ashby', slug: 'salient' },
  { name: 'Sana', ats: 'ashby', slug: 'sana-roles' },
  { name: 'SandboxAQ', ats: 'ashby', slug: 'sandboxaq' },
  { name: 'Sardine', ats: 'ashby', slug: 'sardine' },
  { name: 'Sarj.ai', ats: 'ashby', slug: 'sarjai' },
  { name: 'Savvy Trellis', ats: 'ashby', slug: 'savvyinsurance-trellis' },
  { name: 'Scale Army', ats: 'ashby', slug: 'Scale Army Careers' },
  { name: 'Scribe', ats: 'ashby', slug: 'scribe' },
  { name: 'SE3 Labs', ats: 'ashby', slug: 'se3' },
  { name: 'Semgrep', ats: 'ashby', slug: 'semgrep' },
  { name: 'Sensmore', ats: 'ashby', slug: 'sensmore' },
  { name: 'SentiLink', ats: 'ashby', slug: 'sentilink' },
  { name: 'Serve Robotics', ats: 'ashby', slug: 'serverobotics' },
  { name: 'SF Compute', ats: 'ashby', slug: 'sfcompute' },
  { name: 'ShiftKey', ats: 'ashby', slug: 'shiftkey' },
  { name: 'Siena AI', ats: 'ashby', slug: 'siena' },
  { name: 'Sierra', ats: 'ashby', slug: 'Sierra' },
  { name: 'SigNoz', ats: 'ashby', slug: 'SigNoz' },
  { name: 'Silver', ats: 'ashby', slug: 'silver' },
  { name: 'Sola', ats: 'ashby', slug: 'sola' },
  { name: 'Sphere', ats: 'ashby', slug: 'sphere' },
  { name: 'Statsig', ats: 'ashby', slug: 'statsig' },
  { name: 'Substack', ats: 'ashby', slug: 'substack' },
  { name: 'Sui Foundation', ats: 'ashby', slug: 'sui foundation' },
  { name: 'Sunday', ats: 'ashby', slug: 'sunday' },
  { name: 'Suno', ats: 'ashby', slug: 'suno' },
  { name: 'Supabase', ats: 'ashby', slug: 'supabase' },
  { name: 'Super.com', ats: 'ashby', slug: 'super.com' },
  { name: 'Svix', ats: 'ashby', slug: 'svix' },
  { name: 'Sybill AI', ats: 'ashby', slug: 'sybill-ai' },
  { name: 'Sygaldry Technologies', ats: 'ashby', slug: 'sygaldry-technologies' },
  { name: 'Synthesia', ats: 'ashby', slug: 'synthesia' },
  { name: 'Synthflow', ats: 'ashby', slug: 'synthflow' },
  { name: 'Tacto', ats: 'ashby', slug: 'tacto' },
  { name: 'Tailor', ats: 'ashby', slug: 'tailor' },
  { name: 'Tandem', ats: 'ashby', slug: 'tandem' },
  { name: 'Tavus', ats: 'ashby', slug: 'tavus' },
  { name: 'Taxfix', ats: 'ashby', slug: 'taxfix.com' },
  { name: 'Techtorch', ats: 'ashby', slug: 'techtorch' },
  { name: 'Tennr', ats: 'ashby', slug: 'tennr' },
  { name: 'Tenor', ats: 'ashby', slug: 'tenor' },
  { name: 'Terminal Industries', ats: 'ashby', slug: 'terminal-industries' },
  { name: 'Tessera Labs', ats: 'ashby', slug: 'tessera-labs' },
  { name: 'The Apex Project', ats: 'ashby', slug: 'the apex project' },
  { name: 'The Browser Company', ats: 'ashby', slug: 'The Browser Company' },
  { name: 'Tilt HQ', ats: 'ashby', slug: 'tilthq' },
  { name: 'TLDR', ats: 'ashby', slug: 'tldr.tech' },
  { name: 'Traversal', ats: 'ashby', slug: 'traversal' },
  { name: 'Traysar', ats: 'ashby', slug: 'traysar' },
  { name: 'Truelogic', ats: 'ashby', slug: 'truelogic' },
  { name: 'turbopuffer', ats: 'ashby', slug: 'turbopuffer' },
  { name: 'TwelveLabs', ats: 'ashby', slug: 'twelve-labs' },
  { name: 'Uniswap', ats: 'ashby', slug: 'uniswap' },
  { name: 'UnlikelyAI', ats: 'ashby', slug: 'unlikelyai' },
  { name: 'UpCodes', ats: 'ashby', slug: 'UpCodes' },
  { name: 'Upside', ats: 'ashby', slug: 'upside' },
  { name: 'Vapi', ats: 'ashby', slug: 'vapi' },
  { name: 'Varick Agents', ats: 'ashby', slug: 'Varick-Agents' },
  { name: 'Vellum', ats: 'ashby', slug: 'vellum' },
  { name: 'VibeCode', ats: 'ashby', slug: 'vibecode' },
  { name: 'Vibiz', ats: 'ashby', slug: 'vibiz' },
  { name: 'Videa.ai', ats: 'ashby', slug: 'videa.ai' },
  { name: 'VIDRUSH', ats: 'ashby', slug: 'vidrush' },
  { name: 'Virta Health', ats: 'ashby', slug: 'virtahealth' },
  { name: 'Wealthsimple', ats: 'ashby', slug: 'wealthsimple' },
  { name: 'Weave Work', ats: 'ashby', slug: 'workweave' },
  { name: 'Weaviate', ats: 'ashby', slug: 'weaviate' },
  { name: 'Weekend', ats: 'ashby', slug: 'weekend' },
  { name: 'Whatnot', ats: 'ashby', slug: 'whatnot' },
  { name: 'Windranger Labs', ats: 'ashby', slug: 'windranger' },
  { name: 'Wisdom AI', ats: 'ashby', slug: 'Wisdom AI' },
  { name: 'Wispr Flow', ats: 'ashby', slug: 'wispr-flow' },
  { name: 'WorkOS', ats: 'ashby', slug: 'workos' },
  { name: 'Workshop Labs', ats: 'ashby', slug: 'workshoplabs' },
  { name: 'Wraithwatch', ats: 'ashby', slug: 'wraithwatch' },
  { name: 'Y Combinator', ats: 'ashby', slug: 'ycombinator' },
  { name: 'Zapier', ats: 'ashby', slug: 'zapier' },
  { name: 'Zencastr', ats: 'ashby', slug: 'zencastr' },
  { name: 'Zip (Ashby)', ats: 'ashby', slug: 'zip' },
  { name: 'Zydro', ats: 'ashby', slug: 'zydro' },
]

// ── Lever candidates from agent ──────────────────────────────────────────────
const LEVER: Candidate[] = [
  { name: '1inch', ats: 'lever', slug: '1inch' },
  { name: 'Actian', ats: 'lever', slug: 'actian' },
  { name: 'ActiveCampaign', ats: 'lever', slug: 'activecampaign' },
  { name: 'Aethos Hotels', ats: 'lever', slug: 'aethoshotels' },
  { name: 'airSlate', ats: 'lever', slug: 'airslate' },
  { name: 'Aledade', ats: 'lever', slug: 'aledade' },
  { name: 'Allegiant', ats: 'lever', slug: 'allegiantair' },
  { name: 'Alloy', ats: 'lever', slug: 'alloy' },
  { name: 'Altarum', ats: 'lever', slug: 'altarum' },
  { name: 'AngelList', ats: 'lever', slug: 'angellist' },
  { name: 'AppFollow', ats: 'lever', slug: 'appfollow' },
  { name: 'AppZen', ats: 'lever', slug: 'appzen' },
  { name: "Arc'teryx", ats: 'lever', slug: 'arcteryx.com' },
  { name: 'Artera', ats: 'lever', slug: 'artera' },
  { name: 'Ataccama', ats: 'lever', slug: 'ataccama' },
  { name: 'Basis', ats: 'lever', slug: 'basis' },
  { name: 'Bazaarvoice', ats: 'lever', slug: 'bazaarvoice' },
  { name: 'Best Egg', ats: 'lever', slug: 'BestEgg' },
  { name: 'Binance', ats: 'lever', slug: 'binance' },
  { name: 'BlackCloak', ats: 'lever', slug: 'BlackCloak' },
  { name: 'Brevo', ats: 'lever', slug: 'brevo' },
  { name: 'CareMessage', ats: 'lever', slug: 'caremessage' },
  { name: 'CertiK', ats: 'lever', slug: 'certik' },
  { name: 'ChowNow', ats: 'lever', slug: 'chownow' },
  { name: 'CI&T', ats: 'lever', slug: 'ciandt' },
  { name: 'Clari', ats: 'lever', slug: 'clari' },
  { name: 'Coalfire', ats: 'lever', slug: 'coalfire' },
  { name: 'co:collective', ats: 'lever', slug: 'cocollective' },
  { name: 'Codeway', ats: 'lever', slug: 'codeway' },
  { name: 'Collabora', ats: 'lever', slug: 'collabora' },
  { name: 'Collate', ats: 'lever', slug: 'collate' },
  { name: 'Coupa', ats: 'lever', slug: 'coupa' },
  { name: 'Crypto.com', ats: 'lever', slug: 'crypto' },
  { name: 'DeleteMe', ats: 'lever', slug: 'deleteme' },
  { name: 'Despegar', ats: 'lever', slug: 'despegar' },
  { name: 'Dexterity', ats: 'lever', slug: 'dexterity' },
  { name: 'Drivetrain', ats: 'lever', slug: 'drivetrain' },
  { name: 'Encord', ats: 'lever', slug: 'CordTechnologies' },
  { name: 'e.l.f. Beauty', ats: 'lever', slug: 'elfbeauty' },
  { name: 'ERG', ats: 'lever', slug: 'erg' },
  { name: 'Evry Health', ats: 'lever', slug: 'evry-health' },
  { name: 'Farfetch', ats: 'lever', slug: 'farfetch' },
  { name: 'Finix', ats: 'lever', slug: 'finix' },
  { name: 'FiscalNote', ats: 'lever', slug: 'fiscalnote' },
  { name: 'Foodsmart', ats: 'lever', slug: 'foodsmart' },
  { name: 'Gate.io', ats: 'lever', slug: 'gate' },
  { name: 'Glide', ats: 'lever', slug: 'glide' },
  { name: 'Gopuff', ats: 'lever', slug: 'gopuff' },
  { name: 'GoodLeap', ats: 'lever', slug: 'goodleap' },
  { name: 'Greenlight', ats: 'lever', slug: 'greenlight' },
  { name: 'H1', ats: 'lever', slug: 'h1' },
  { name: 'HappyCo', ats: 'lever', slug: 'happyco' },
  { name: 'Hevo Data', ats: 'lever', slug: 'hevodata' },
  { name: 'HHAeXchange', ats: 'lever', slug: 'hhaexchange' },
  { name: 'HighLevel', ats: 'lever', slug: 'gohighlevel' },
  { name: 'Hive', ats: 'lever', slug: 'hive' },
  { name: 'HONK', ats: 'lever', slug: 'honkforhelp' },
  { name: 'Hostinger', ats: 'lever', slug: 'hostinger' },
  { name: 'Houzz', ats: 'lever', slug: 'houzz' },
  { name: 'Immuta', ats: 'lever', slug: 'immuta' },
  { name: 'Immutable', ats: 'lever', slug: 'immutable' },
  { name: 'Included Health', ats: 'lever', slug: 'includedhealth' },
  { name: 'Insider', ats: 'lever', slug: 'insiderone' },
  { name: 'Instrument', ats: 'lever', slug: 'instrument' },
  { name: 'Jam City', ats: 'lever', slug: 'jamcity' },
  { name: 'JetBridge', ats: 'lever', slug: 'JetBridge' },
  { name: 'JioStar', ats: 'lever', slug: 'jiostar' },
  { name: 'JumpCloud', ats: 'lever', slug: 'jumpcloud' },
  { name: 'Jupe', ats: 'lever', slug: 'jupe' },
  { name: 'Kiddom', ats: 'lever', slug: 'kiddom' },
  { name: 'Kraken Technologies', ats: 'lever', slug: 'kraken123' },
  { name: 'Legend', ats: 'lever', slug: 'Legend' },
  { name: 'Level AI', ats: 'lever', slug: 'levelai' },
  { name: 'LogRocket', ats: 'lever', slug: 'logrocket' },
  { name: 'Luxury Presence', ats: 'lever', slug: 'luxurypresence' },
  { name: 'Match Group', ats: 'lever', slug: 'matchgroup' },
  { name: 'Matillion', ats: 'lever', slug: 'matillion' },
  { name: 'Mediafly', ats: 'lever', slug: 'Mediafly' },
  { name: 'Mistplay', ats: 'lever', slug: 'mistplay' },
  { name: 'Mistral AI', ats: 'lever', slug: 'mistral' },
  { name: 'MoonPay', ats: 'lever', slug: 'moonpay' },
  { name: 'Mujin', ats: 'lever', slug: 'mujininc' },
  { name: 'Neon', ats: 'lever', slug: 'neon' },
  { name: 'Neuron7', ats: 'lever', slug: 'neuron7' },
  { name: 'Nova Talent', ats: 'lever', slug: 'novatalent' },
  { name: 'nXscale Solutions', ats: 'lever', slug: 'nxscale' },
  { name: 'Octopus Energy', ats: 'lever', slug: 'octoenergy' },
  { name: 'Offchain Labs', ats: 'lever', slug: 'offchainlabs' },
  { name: 'Oktopost', ats: 'lever', slug: 'oktopost' },
  { name: 'Olo', ats: 'lever', slug: 'olo' },
  { name: 'Omnisend', ats: 'lever', slug: 'omnisend' },
  { name: 'Orca Bio', ats: 'lever', slug: 'orcabiosystems' },
  { name: 'Outsight', ats: 'lever', slug: 'outsight' },
  { name: 'PacerPro', ats: 'lever', slug: 'PacerPro' },
  { name: 'PeopleGrove', ats: 'lever', slug: 'peoplegrove' },
  { name: 'Percona', ats: 'lever', slug: 'percona' },
  { name: 'Prismic', ats: 'lever', slug: 'prismic' },
  { name: 'Proof', ats: 'lever', slug: 'proof' },
  { name: 'Radical AI', ats: 'lever', slug: 'RadicalAI' },
  { name: 'Rapt Studio', ats: 'lever', slug: 'RaptStudio' },
  { name: 'Regard', ats: 'lever', slug: 'Regard' },
  { name: 'Rise', ats: 'lever', slug: 'rise' },
  { name: 'Ro', ats: 'lever', slug: 'ro' },
  { name: 'Saviynt', ats: 'lever', slug: 'saviynt' },
  { name: 'Scaleway', ats: 'lever', slug: 'scaleway' },
  { name: 'Shield AI', ats: 'lever', slug: 'shieldai' },
  { name: 'SiteGround', ats: 'lever', slug: 'siteground' },
  { name: 'Smart Working Solutions', ats: 'lever', slug: 'smart-working-solutions' },
  { name: 'SoloPulse', ats: 'lever', slug: 'solopulseco' },
  { name: 'Spark Climate Solutions', ats: 'lever', slug: 'SparkClimateSolutions' },
  { name: 'Spreetail', ats: 'lever', slug: 'spreetail' },
  { name: 'StartEngine', ats: 'lever', slug: 'startengine' },
  { name: 'SuperAnnotate', ats: 'lever', slug: 'superannotate' },
  { name: 'SynMax', ats: 'lever', slug: 'synmax' },
  { name: 'Sword Health', ats: 'lever', slug: 'swordhealth' },
  { name: 'Tagup', ats: 'lever', slug: 'tagup' },
  { name: 'Tala', ats: 'lever', slug: 'tala' },
  { name: 'Termgrid', ats: 'lever', slug: 'termgrid' },
  { name: 'Terraformation', ats: 'lever', slug: 'Terraformation' },
  { name: 'TextNow', ats: 'lever', slug: 'textnow' },
  { name: 'Thinkingbox', ats: 'lever', slug: 'thinkingbox' },
  { name: 'ThinkAHEAD', ats: 'lever', slug: 'thinkahead' },
  { name: 'Toptal', ats: 'lever', slug: 'toptal' },
  { name: 'Trendyol', ats: 'lever', slug: 'trendyol' },
  { name: 'True Platform', ats: 'lever', slug: 'trueplatform' },
  { name: 'Trustly', ats: 'lever', slug: 'trustly' },
  { name: 'Turgon AI', ats: 'lever', slug: 'turgon-ai' },
  { name: 'Tutor Intelligence', ats: 'lever', slug: 'tutorintelligence' },
  { name: 'UpGuard', ats: 'lever', slug: 'upguard' },
  { name: 'US Mobile', ats: 'lever', slug: 'USMobile' },
  { name: 'Veda Tech Labs', ats: 'lever', slug: 'vedatechlabs' },
  { name: 'Veepee', ats: 'lever', slug: 'veepee' },
  { name: 'Vestiaire Collective', ats: 'lever', slug: 'vestiairecollective' },
  { name: 'Viget', ats: 'lever', slug: 'viget' },
  { name: 'VRChat', ats: 'lever', slug: 'vrchat' },
  { name: 'WatchGuard', ats: 'lever', slug: 'watchguard' },
  { name: 'Wealthfront', ats: 'lever', slug: 'wealthfront' },
  { name: 'Woven by Toyota', ats: 'lever', slug: 'woven-by-toyota' },
  { name: 'Xsolla', ats: 'lever', slug: 'xsolla' },
  { name: 'Zeta', ats: 'lever', slug: 'zeta' },
  { name: 'Zocks', ats: 'lever', slug: 'zocks' },
  { name: 'Zopa', ats: 'lever', slug: 'zopa' },
]

// ── SmartRecruiters candidates from agent ────────────────────────────────────
const SMARTRECRUITERS: Candidate[] = [
  { name: 'AbbVie', ats: 'smartrecruiters', slug: 'AbbVie' },
  { name: 'ASICS', ats: 'smartrecruiters', slug: 'Asics' },
  { name: 'ASOS', ats: 'smartrecruiters', slug: 'Asos' },
  { name: 'Avery Dennison', ats: 'smartrecruiters', slug: 'AveryDennison' },
  { name: 'bet365', ats: 'smartrecruiters', slug: 'Bet3651' },
  { name: 'Bosch Group', ats: 'smartrecruiters', slug: 'BoschGroup' },
  { name: 'Christian Brothers Automotive', ats: 'smartrecruiters', slug: 'ChristianBrothersAutomotive' },
  { name: 'Colliers', ats: 'smartrecruiters', slug: 'Colliers' },
  { name: 'Delivery Hero', ats: 'smartrecruiters', slug: 'DeliveryHero' },
  { name: 'Deloitte NL', ats: 'smartrecruiters', slug: 'DeloitteNL' },
  { name: 'Devoteam', ats: 'smartrecruiters', slug: 'Devoteam' },
  { name: "Domino's", ats: 'smartrecruiters', slug: 'Dominos' },
  { name: 'Equinox', ats: 'smartrecruiters', slug: 'Equinox' },
  { name: 'Expeditors', ats: 'smartrecruiters', slug: 'Expeditors' },
  { name: 'Experian', ats: 'smartrecruiters', slug: 'Experian' },
  { name: 'Foster Farms', ats: 'smartrecruiters', slug: 'FosterFarms' },
  { name: 'Frasers Group', ats: 'smartrecruiters', slug: 'FrasersGroup' },
  { name: 'Freshworks', ats: 'smartrecruiters', slug: 'Freshworks' },
  { name: 'Gameloft', ats: 'smartrecruiters', slug: 'Gameloft' },
  { name: 'INTERMARCHE', ats: 'smartrecruiters', slug: 'Intermarche' },
  { name: 'Jobs for Humanity', ats: 'smartrecruiters', slug: 'JobsforHumanity' },
  { name: 'JYSK', ats: 'smartrecruiters', slug: 'JYSK' },
  { name: 'LinkedIn', ats: 'smartrecruiters', slug: 'LinkedIn3' },
  { name: 'Lonza', ats: 'smartrecruiters', slug: 'Lonza' },
  { name: 'McDonalds Canada', ats: 'smartrecruiters', slug: 'McDonaldsCanada' },
  { name: 'MindTickle', ats: 'smartrecruiters', slug: 'Mindtickle' },
  { name: 'Nine', ats: 'smartrecruiters', slug: 'Nine' },
  { name: 'Primark', ats: 'smartrecruiters', slug: 'Primark' },
  { name: 'Public Storage', ats: 'smartrecruiters', slug: 'PublicStorage' },
  { name: 'Red Bull', ats: 'smartrecruiters', slug: 'RedBull' },
  { name: 'ServiceNow', ats: 'smartrecruiters', slug: 'ServiceNow' },
  { name: 'SmartRecruiters', ats: 'smartrecruiters', slug: 'SmartRecruiters' },
  { name: 'Sodexo', ats: 'smartrecruiters', slug: 'Sodexo' },
  { name: 'The Nielsen Company', ats: 'smartrecruiters', slug: 'TheNielsenCompany' },
  { name: 'The Wonderful Company', ats: 'smartrecruiters', slug: 'TheWonderfulCompany' },
  { name: 'Tipico', ats: 'smartrecruiters', slug: 'Tipico' },
  { name: 'Vattenfall', ats: 'smartrecruiters', slug: 'Vattenfall' },
  { name: 'Visa', ats: 'smartrecruiters', slug: 'Visa' },
  { name: 'Western Digital', ats: 'smartrecruiters', slug: 'WesternDigital' },
  { name: 'Xplor', ats: 'smartrecruiters', slug: 'Xplor' },
]

// ── Dedupe and print ─────────────────────────────────────────────────────────

function dedupe(candidates: Candidate[]): Candidate[] {
  const existingByName = new Set(
    ATS_COMPANIES.map((c) => c.name.toLowerCase().trim()),
  )
  const existingBySlug = new Set(
    ATS_COMPANIES.filter((c) => c.ats !== 'workday').map(
      (c) => `${c.ats}:${(c as { slug: string }).slug.toLowerCase()}`,
    ),
  )
  const seenInThisBatch = new Set<string>()
  const out: Candidate[] = []
  let skipped = 0
  for (const c of candidates) {
    const nameKey = c.name.toLowerCase().trim()
    const slugKey = `${c.ats}:${c.slug.toLowerCase()}`
    if (existingByName.has(nameKey) || existingBySlug.has(slugKey)) {
      skipped++
      continue
    }
    if (seenInThisBatch.has(nameKey) || seenInThisBatch.has(slugKey)) {
      skipped++
      continue
    }
    seenInThisBatch.add(nameKey)
    seenInThisBatch.add(slugKey)
    out.push(c)
  }
  console.error(`[${candidates[0]?.ats ?? '?'}] accepted=${out.length} skipped=${skipped}`)
  return out
}

function format(c: Candidate): string {
  const name = c.name.replace(/'/g, "\\'")
  return `  { name: '${name}', ats: '${c.ats}', slug: '${c.slug}' },`
}

const gh = dedupe(GREENHOUSE).sort((a, b) => a.name.localeCompare(b.name))
const as = dedupe(ASHBY).sort((a, b) => a.name.localeCompare(b.name))
const lv = dedupe(LEVER).sort((a, b) => a.name.localeCompare(b.name))
const sr = dedupe(SMARTRECRUITERS).sort((a, b) => a.name.localeCompare(b.name))

console.log('// ── Greenhouse additions (batch 2) ──────────────────────────────────────')
for (const c of gh) console.log(format(c))
console.log()
console.log('// ── Ashby additions (batch 2) ───────────────────────────────────────────')
for (const c of as) console.log(format(c))
console.log()
console.log('// ── Lever additions (batch 2) ───────────────────────────────────────────')
for (const c of lv) console.log(format(c))
console.log()
console.log('// ── SmartRecruiters additions (batch 2) ─────────────────────────────────')
for (const c of sr) console.log(format(c))
console.log()
console.error(`\nTotal additions: ${gh.length + as.length + lv.length + sr.length}`)
console.error(`Grand total ATS whitelist: ${ATS_COMPANIES.length + gh.length + as.length + lv.length + sr.length}`)
