// Registry of target companies and their ATS platform + slug

export type AtsType = 'greenhouse' | 'lever' | 'ashby' | 'smartrecruiters' | 'icims' | 'workday'

export interface StandardAtsCompany {
  name: string   // display name — must match companies.ts for tier lookup
  ats: Exclude<AtsType, 'workday'>
  slug: string   // slug used in ATS API URL
}

export interface WorkdayCompany {
  name: string
  ats: 'workday'
  host: string        // e.g. "nvidia.wd5.myworkdayjobs.com" — the tenant host
  site: string        // e.g. "NVIDIAExternalCareerSite" — the external career site name
  locale?: string     // e.g. "en-US" — omitted if the board has no locale segment
  boardUrl?: string   // optional override for the Referer header; defaults to `https://{host}/`
}

export type AtsCompany = StandardAtsCompany | WorkdayCompany

export const ATS_COMPANIES: AtsCompany[] = [
  // ── Greenhouse ────────────────────────────────────────────────────────────
  { name: '10x Genomics', ats: 'greenhouse', slug: '10xgenomics' },
  { name: '15Five', ats: 'greenhouse', slug: '15five' },
  { name: '1Password', ats: 'greenhouse', slug: '1password' },
  { name: 'AbCellera', ats: 'greenhouse', slug: 'abcellera' },
  { name: 'Abnormal Security', ats: 'greenhouse', slug: 'abnormalsecurity' },
  { name: 'Absci', ats: 'greenhouse', slug: 'absci' },
  { name: 'Accolade', ats: 'greenhouse', slug: 'accolade' },
  { name: 'Affirm', ats: 'greenhouse', slug: 'affirm' },
  { name: 'Airbase', ats: 'greenhouse', slug: 'airbase' },
  { name: 'Airbnb', ats: 'greenhouse', slug: 'airbnb' },
  { name: 'Airbyte', ats: 'greenhouse', slug: 'airbyte' },
  { name: 'Airtable', ats: 'greenhouse', slug: 'airtable' },
  { name: 'Alation', ats: 'greenhouse', slug: 'alation' },
  { name: 'Alchemy', ats: 'greenhouse', slug: 'alchemy' },
  { name: 'Algolia', ats: 'greenhouse', slug: 'algolia' },
  { name: 'Amplitude', ats: 'greenhouse', slug: 'amplitude' },
  { name: 'Anduril', ats: 'greenhouse', slug: 'andurilindustries' },
  { name: 'Anthropic', ats: 'greenhouse', slug: 'anthropic' },
  { name: 'Apollo', ats: 'greenhouse', slug: 'apolloio' },
  { name: 'Appcues', ats: 'greenhouse', slug: 'appcues' },
  { name: 'Applied Intuition', ats: 'greenhouse', slug: 'appliedintuition' },
  { name: 'Applovin', ats: 'greenhouse', slug: 'applovin' },
  { name: 'Asana', ats: 'greenhouse', slug: 'asana' },
  { name: 'Attentive', ats: 'greenhouse', slug: 'attentive' },
  { name: 'Benchling', ats: 'greenhouse', slug: 'benchling' },
  { name: 'Betterworks', ats: 'greenhouse', slug: 'betterworks' },
  { name: 'BILL', ats: 'greenhouse', slug: 'billcom' },
  { name: 'Blend', ats: 'greenhouse', slug: 'blend' },
  { name: 'Bloomreach', ats: 'greenhouse', slug: 'bloomreach' },
  { name: 'Box', ats: 'greenhouse', slug: 'box' },
  { name: 'Braze', ats: 'greenhouse', slug: 'braze' },
  { name: 'Brex', ats: 'greenhouse', slug: 'brex' },
  { name: 'Buildkite', ats: 'greenhouse', slug: 'buildkite' },
  { name: 'Butterfly Network', ats: 'greenhouse', slug: 'butterflynetwork' },
  { name: 'C3.ai', ats: 'greenhouse', slug: 'c3ai' },
  { name: 'Calm', ats: 'greenhouse', slug: 'calm' },
  { name: 'Canva', ats: 'greenhouse', slug: 'canva' },
  { name: 'CarGurus', ats: 'greenhouse', slug: 'cargurus' },
  { name: 'Carta', ats: 'greenhouse', slug: 'carta' },
  { name: 'Cedar', ats: 'greenhouse', slug: 'cedar' },
  { name: 'Cerebras Systems', ats: 'greenhouse', slug: 'cerebrassystems' },
  { name: 'Chainalysis', ats: 'greenhouse', slug: 'chainalysis' },
  { name: 'Checkr', ats: 'greenhouse', slug: 'checkr' },
  { name: 'Chime', ats: 'greenhouse', slug: 'chime' },
  { name: 'Chronosphere', ats: 'greenhouse', slug: 'chronosphere' },
  { name: 'Circle', ats: 'greenhouse', slug: 'circle' },
  { name: 'Cityblock Health', ats: 'greenhouse', slug: 'cityblockhealth' },
  { name: 'ClickHouse', ats: 'greenhouse', slug: 'clickhouse' },
  { name: 'ClickUp', ats: 'greenhouse', slug: 'clickup' },
  { name: 'Clio', ats: 'greenhouse', slug: 'clio' },
  { name: 'Cloudflare', ats: 'greenhouse', slug: 'cloudflare' },
  { name: 'Cloudinary', ats: 'greenhouse', slug: 'cloudinary' },
  { name: 'Cockroach Labs', ats: 'greenhouse', slug: 'cockroachlabs' },
  { name: 'Cohere', ats: 'greenhouse', slug: 'cohere' },
  { name: 'Coinbase', ats: 'greenhouse', slug: 'coinbase' },
  { name: 'Collibra', ats: 'greenhouse', slug: 'collibra' },
  { name: 'Color Health', ats: 'greenhouse', slug: 'colorhealth' },
  { name: 'Column', ats: 'greenhouse', slug: 'column' },
  { name: 'Compass', ats: 'greenhouse', slug: 'compass' },
  { name: 'Confluent', ats: 'greenhouse', slug: 'confluentinc' },
  { name: 'Contentful', ats: 'greenhouse', slug: 'contentful' },
  { name: 'Contentsquare', ats: 'greenhouse', slug: 'contentsquare' },
  { name: 'Contentstack', ats: 'greenhouse', slug: 'contentstack' },
  { name: 'Coursera', ats: 'greenhouse', slug: 'coursera' },
  { name: 'Culture Amp', ats: 'greenhouse', slug: 'cultureamp' },
  { name: 'Customer.io', ats: 'greenhouse', slug: 'customerio' },
  { name: 'Databricks', ats: 'greenhouse', slug: 'databricks' },
  { name: 'Datadog', ats: 'greenhouse', slug: 'datadog' },
  { name: 'Datavant', ats: 'greenhouse', slug: 'datavant' },
  { name: 'dbt Labs', ats: 'greenhouse', slug: 'dbtlabs' },
  { name: 'Deel', ats: 'greenhouse', slug: 'deel' },
  { name: 'Definitive Healthcare', ats: 'greenhouse', slug: 'definitivehealthcare' },
  { name: 'Devoted Health', ats: 'greenhouse', slug: 'devotedhealth' },
  { name: 'Dialpad', ats: 'greenhouse', slug: 'dialpad' },
  { name: 'Discord', ats: 'greenhouse', slug: 'discord' },
  { name: 'DoorDash', ats: 'greenhouse', slug: 'doordashusa' },
  { name: 'Dovetail', ats: 'greenhouse', slug: 'dovetailapp' },
  { name: 'Doximity', ats: 'greenhouse', slug: 'doximity' },
  { name: 'Drata', ats: 'greenhouse', slug: 'drata' },
  { name: 'Dropbox', ats: 'greenhouse', slug: 'dropbox' },
  { name: 'Duolingo', ats: 'greenhouse', slug: 'duolingo' },
  { name: 'Eightfold AI', ats: 'greenhouse', slug: 'eightfoldai' },
  { name: 'Elastic', ats: 'greenhouse', slug: 'elastic' },
  { name: 'Epic Games', ats: 'greenhouse', slug: 'epicgames' },
  { name: 'Evisort', ats: 'greenhouse', slug: 'evisort' },
  { name: 'Faire', ats: 'greenhouse', slug: 'faire' },
  { name: 'Fastly', ats: 'greenhouse', slug: 'fastly' },
  { name: 'Figma', ats: 'greenhouse', slug: 'figma' },
  { name: 'Fireblocks', ats: 'greenhouse', slug: 'fireblocks' },
  { name: 'Fivetran', ats: 'greenhouse', slug: 'fivetran' },
  { name: 'Flatiron Health', ats: 'greenhouse', slug: 'flatironhealth' },
  { name: 'Flexport', ats: 'greenhouse', slug: 'flexport' },
  { name: 'Front', ats: 'greenhouse', slug: 'front' },
  { name: 'FullStory', ats: 'greenhouse', slug: 'fullstory' },
  { name: 'Gemini', ats: 'greenhouse', slug: 'gemini' },
  { name: 'Ginkgo Bioworks', ats: 'greenhouse', slug: 'ginkgobioworks' },
  { name: 'GitLab', ats: 'greenhouse', slug: 'gitlab' },
  { name: 'Gladly', ats: 'greenhouse', slug: 'gladly' },
  { name: 'Glean', ats: 'greenhouse', slug: 'glean' },
  { name: 'Gong', ats: 'greenhouse', slug: 'gong' },
  { name: 'Grafana Labs', ats: 'greenhouse', slug: 'grafanalabs' },
  { name: 'Grammarly', ats: 'greenhouse', slug: 'superhuman' },
  { name: 'Gusto', ats: 'greenhouse', slug: 'gusto' },
  { name: 'Harness', ats: 'greenhouse', slug: 'harness' },
  { name: 'Heap', ats: 'greenhouse', slug: 'heap' },
  { name: 'HelloFresh', ats: 'greenhouse', slug: 'hellofresh' },
  { name: 'Highspot', ats: 'greenhouse', slug: 'highspot' },
  { name: 'Hims & Hers', ats: 'greenhouse', slug: 'forhims' },
  { name: 'Honeycomb', ats: 'greenhouse', slug: 'honeycomb' },
  { name: 'HubSpot', ats: 'greenhouse', slug: 'hubspot' },
  { name: 'Huntress', ats: 'greenhouse', slug: 'huntress' },
  { name: 'Instacart', ats: 'greenhouse', slug: 'instacart' },
  { name: 'Intapp', ats: 'greenhouse', slug: 'intapp' },
  { name: 'Intercom', ats: 'greenhouse', slug: 'intercom' },
  { name: 'Ironclad', ats: 'greenhouse', slug: 'ironcladapp' },
  { name: 'Iterable', ats: 'greenhouse', slug: 'iterable' },
  { name: 'Justworks', ats: 'greenhouse', slug: 'justworks' },
  { name: 'Khan Academy', ats: 'greenhouse', slug: 'khanacademy' },
  { name: 'Klaviyo', ats: 'greenhouse', slug: 'klaviyo' },
  { name: 'Kraken', ats: 'greenhouse', slug: 'kraken' },
  { name: 'Lattice', ats: 'greenhouse', slug: 'lattice' },
  { name: 'LaunchDarkly', ats: 'greenhouse', slug: 'launchdarkly' },
  { name: 'Leapsome', ats: 'greenhouse', slug: 'leapsome' },
  { name: 'Lime', ats: 'greenhouse', slug: 'lime' },
  { name: 'Locus Robotics', ats: 'greenhouse', slug: 'locusrobotics' },
  { name: 'Lucid Software', ats: 'greenhouse', slug: 'lucidsoftware' },
  { name: 'Lyft', ats: 'greenhouse', slug: 'lyft' },
  { name: 'Lyra Health', ats: 'greenhouse', slug: 'lyrahealth' },
  { name: 'Marqeta', ats: 'greenhouse', slug: 'marqeta' },
  { name: 'Materialize', ats: 'greenhouse', slug: 'materialize' },
  { name: 'Medallia', ats: 'greenhouse', slug: 'medallia' },
  { name: 'Melio', ats: 'greenhouse', slug: 'melio' },
  { name: 'Mercury', ats: 'greenhouse', slug: 'mercury' },
  { name: 'Metabase', ats: 'greenhouse', slug: 'metabase' },
  { name: 'Mixpanel', ats: 'greenhouse', slug: 'mixpanel' },
  { name: 'Modern Treasury', ats: 'greenhouse', slug: 'moderntreasury' },
  { name: 'Monday.com', ats: 'greenhouse', slug: 'mondaydotcom' },
  { name: 'MongoDB', ats: 'greenhouse', slug: 'mongodb' },
  { name: 'Monte Carlo', ats: 'greenhouse', slug: 'montecarlodata' },
  { name: 'Moveworks', ats: 'greenhouse', slug: 'moveworks' },
  { name: 'Nano-X Imaging', ats: 'greenhouse', slug: 'nanox' },
  { name: 'Navan', ats: 'greenhouse', slug: 'navan' },
  { name: 'nCino', ats: 'greenhouse', slug: 'ncino' },
  { name: 'Netlify', ats: 'greenhouse', slug: 'netlify' },
  { name: 'New Relic', ats: 'greenhouse', slug: 'newrelic' },
  { name: 'Niantic', ats: 'greenhouse', slug: 'niantic' },
  { name: 'Nuro', ats: 'greenhouse', slug: 'nuro' },
  { name: 'Okta', ats: 'greenhouse', slug: 'okta' },
  { name: 'OpenAI', ats: 'greenhouse', slug: 'openai' },
  { name: 'Opendoor', ats: 'greenhouse', slug: 'opendoor' },
  { name: 'Optimizely', ats: 'greenhouse', slug: 'optimizely' },
  { name: 'Orca Security', ats: 'greenhouse', slug: 'orcasecurity' },
  { name: 'Oscar Health', ats: 'greenhouse', slug: 'oscarhealth' },
  { name: 'Outreach', ats: 'greenhouse', slug: 'outreach' },
  { name: 'PagerDuty', ats: 'greenhouse', slug: 'pagerduty' },
  { name: 'Palantir', ats: 'greenhouse', slug: 'palantir' },
  { name: 'Paxos', ats: 'greenhouse', slug: 'paxos' },
  { name: 'Pendo', ats: 'greenhouse', slug: 'pendo' },
  { name: 'Perplexity', ats: 'greenhouse', slug: 'perplexity' },
  { name: 'Phenom', ats: 'greenhouse', slug: 'phenom' },
  { name: 'Pinterest', ats: 'greenhouse', slug: 'pinterest' },
  { name: 'Plaid', ats: 'greenhouse', slug: 'plaid' },
  { name: 'PlanetScale', ats: 'greenhouse', slug: 'planetscale' },
  { name: 'Postman', ats: 'greenhouse', slug: 'postmanio' },
  { name: 'Productboard', ats: 'greenhouse', slug: 'productboard' },
  { name: 'Pulumi', ats: 'greenhouse', slug: 'pulumi' },
  { name: 'Quantum Metric', ats: 'greenhouse', slug: 'quantummetric' },
  { name: 'Recharge', ats: 'greenhouse', slug: 'rechargepayments' },
  { name: 'Recursion Pharmaceuticals', ats: 'greenhouse', slug: 'recursionpharma' },
  { name: 'Reddit', ats: 'greenhouse', slug: 'reddit' },
  { name: 'Rippling', ats: 'greenhouse', slug: 'rippling' },
  { name: 'Robinhood', ats: 'greenhouse', slug: 'robinhood' },
  { name: 'Runway', ats: 'greenhouse', slug: 'runwayml' },
  { name: 'Salesloft', ats: 'greenhouse', slug: 'salesloft' },
  { name: 'Samsara', ats: 'greenhouse', slug: 'samsara' },
  { name: 'Schrodinger', ats: 'greenhouse', slug: 'schrodinger' },
  { name: 'Sentry', ats: 'greenhouse', slug: 'sentry' },
  { name: 'Sigma Computing', ats: 'greenhouse', slug: 'sigmacomputing' },
  { name: 'Snorkel AI', ats: 'greenhouse', slug: 'snorkelai' },
  { name: 'Snyk', ats: 'greenhouse', slug: 'snyk' },
  { name: 'SpotHero', ats: 'greenhouse', slug: 'spothero' },
  { name: 'Sprig', ats: 'greenhouse', slug: 'sprig' },
  { name: 'Spring Health', ats: 'greenhouse', slug: 'springhealth' },
  { name: 'Sprout Social', ats: 'greenhouse', slug: 'sproutsocial' },
  { name: 'Squarespace', ats: 'greenhouse', slug: 'squarespace' },
  { name: 'Stripe', ats: 'greenhouse', slug: 'stripe' },
  { name: 'Superhuman', ats: 'greenhouse', slug: 'superhuman' },
  { name: 'Teladoc Health', ats: 'greenhouse', slug: 'teladoc' },
  { name: 'Temporal', ats: 'greenhouse', slug: 'temporal' },
  { name: 'ThoughtSpot', ats: 'greenhouse', slug: 'thoughtspot' },
  { name: 'Thumbtack', ats: 'greenhouse', slug: 'thumbtack' },
  { name: 'Tipalti', ats: 'greenhouse', slug: 'tipalti' },
  { name: 'Toast', ats: 'greenhouse', slug: 'toasttab' },
  { name: 'TripAdvisor', ats: 'greenhouse', slug: 'tripadvisor' },
  { name: 'Twilio', ats: 'greenhouse', slug: 'twilio' },
  { name: 'UserTesting', ats: 'greenhouse', slug: 'usertesting' },
  { name: 'Vanta', ats: 'greenhouse', slug: 'vanta' },
  { name: 'Veeva Systems', ats: 'greenhouse', slug: 'veevasystems' },
  { name: 'Verkada', ats: 'greenhouse', slug: 'verkada' },
  { name: 'WalkMe', ats: 'greenhouse', slug: 'walkme' },
  { name: 'Watershed', ats: 'greenhouse', slug: 'watershed' },
  { name: 'Weave Communications', ats: 'greenhouse', slug: 'weave' },
  { name: 'Wiz', ats: 'greenhouse', slug: 'wiz' },
  { name: 'Workato', ats: 'greenhouse', slug: 'workato' },
  { name: 'Zuora', ats: 'greenhouse', slug: 'zuora' },
  // Additions from audit-filters.ts (companies seen in manual imports)
  { name: 'Baton', ats: 'greenhouse', slug: 'baton' },
  { name: 'BillionToOne', ats: 'greenhouse', slug: 'billiontoone' },
  { name: 'Chalk', ats: 'greenhouse', slug: 'chalkinc' },
  { name: 'Check', ats: 'greenhouse', slug: 'check' },
  { name: 'Extend', ats: 'greenhouse', slug: 'extend' },
  { name: 'Gap International', ats: 'greenhouse', slug: 'gapinternational' },
  { name: 'ID.me', ats: 'greenhouse', slug: 'idme' },
  { name: 'Maven Clinic', ats: 'greenhouse', slug: 'mavenclinic' },
  { name: 'Oldcastle BuildingEnvelope', ats: 'greenhouse', slug: 'oldcastlebuildingenvelope' },
  { name: 'Oura', ats: 'greenhouse', slug: 'oura' },
  { name: 'Rhombus Power', ats: 'greenhouse', slug: 'rhombuspower' },
  { name: 'Roo', ats: 'greenhouse', slug: 'roo' },
  { name: 'Tatari', ats: 'greenhouse', slug: 'tatari' },
  { name: 'Technical Assent', ats: 'greenhouse', slug: 'technicalassent' },
  { name: 'xAI', ats: 'greenhouse', slug: 'xai' },
  // ── iCIMS ────────────────────────────────────────────────────────────────
  { name: 'AMD', ats: 'icims', slug: 'amd' },
  // ── Lever ─────────────────────────────────────────────────────────────────
  { name: 'Calendly', ats: 'lever', slug: 'calendly' },
  { name: 'Chameleon', ats: 'lever', slug: 'chameleon' },
  { name: 'ChartMogul', ats: 'lever', slug: 'chartmogul' },
  { name: 'Chili Piper', ats: 'lever', slug: 'chilipiper' },
  { name: 'Clay', ats: 'lever', slug: 'clay' },
  { name: 'Coda', ats: 'lever', slug: 'coda' },
  { name: 'Descript', ats: 'greenhouse', slug: 'descript' },
  { name: 'Framer', ats: 'lever', slug: 'framer' },
  { name: 'Gamma', ats: 'lever', slug: 'gamma' },
  { name: 'Gem', ats: 'lever', slug: 'gem' },
  { name: 'Gorgias', ats: 'lever', slug: 'gorgias' },
  { name: 'Hex', ats: 'lever', slug: 'hex-technologies' },
  { name: 'Lob', ats: 'lever', slug: 'lob' },
  { name: 'Loop Returns', ats: 'lever', slug: 'loop' },
  { name: 'Maze', ats: 'lever', slug: 'mazedesign' },
  { name: 'Miro', ats: 'lever', slug: 'miro' },
  { name: 'Pitch', ats: 'lever', slug: 'pitch' },
  { name: 'Pocus', ats: 'lever', slug: 'pocus' },
  { name: 'Qualified', ats: 'lever', slug: 'qualified' },
  { name: 'Ramp', ats: 'lever', slug: 'ramp' },
  { name: 'Retool', ats: 'lever', slug: 'retool' },
  { name: 'Scale AI', ats: 'lever', slug: 'scaleai' },
  { name: 'Stytch', ats: 'lever', slug: 'stytch' },
  { name: 'Superside', ats: 'lever', slug: 'superside' },
  { name: 'Tome', ats: 'lever', slug: 'tome' },
  { name: 'TravelPerk', ats: 'lever', slug: 'travelperk' },
  { name: 'Webflow', ats: 'lever', slug: 'webflow' },
  { name: 'Weights & Biases', ats: 'lever', slug: 'wandb' },
  { name: 'Whimsical', ats: 'lever', slug: 'whimsical' },
  { name: 'Writer', ats: 'lever', slug: 'writerai' },
  // Additions from audit-filters.ts (companies seen in manual imports)
  { name: 'BHHC', ats: 'lever', slug: 'bhhc' },
  { name: 'Bumble', ats: 'lever', slug: 'bumbleinc' },
  { name: 'Complex NTWRK', ats: 'lever', slug: 'Complex' },
  { name: 'Lumin Digital', ats: 'lever', slug: 'LuminDigital' },
  { name: 'WHOOP', ats: 'lever', slug: 'whoop' },
  // ── Ashby ─────────────────────────────────────────────────────────────────
  { name: 'Ashby', ats: 'ashby', slug: 'Ashby' },
  { name: 'Circleback', ats: 'ashby', slug: 'circleback' },
  { name: 'Console', ats: 'ashby', slug: 'console' },
  { name: 'Creatify', ats: 'ashby', slug: 'creatify' },
  { name: 'Harvey', ats: 'ashby', slug: 'harvey' },
  { name: 'Hinge Health', ats: 'ashby', slug: 'hinge-health' },
  { name: 'Homebase', ats: 'ashby', slug: 'homebase' },
  { name: 'Koah Labs', ats: 'ashby', slug: 'koahlabs' },
  { name: 'Lindy', ats: 'ashby', slug: 'lindy' },
  { name: 'Luminai', ats: 'ashby', slug: 'luminai' },
  { name: 'Matic Robots', ats: 'ashby', slug: 'Maticrobots' },
  { name: 'P-1 AI', ats: 'ashby', slug: 'P-1 AI' },
  { name: 'Retell AI', ats: 'ashby', slug: 'retell-ai' },
  { name: 'Rogo', ats: 'ashby', slug: 'Rogo' },
  { name: 'Rowspace', ats: 'ashby', slug: 'rowspace' },
  { name: 'Serval', ats: 'ashby', slug: 'Serval' },
  { name: 'Sift', ats: 'ashby', slug: 'siftstack' },
  { name: 'Sleeper', ats: 'ashby', slug: 'sleeper' },
  { name: 'Solace', ats: 'ashby', slug: 'solace' },
  { name: 'Span', ats: 'ashby', slug: 'Span.app' },
  { name: 'Triumph Arcade', ats: 'ashby', slug: 'triumph-arcade' },
  { name: 'Valon', ats: 'ashby', slug: 'Valon' },
  { name: 'Vizcom', ats: 'ashby', slug: 'vizcom' },
  { name: 'Wand', ats: 'ashby', slug: 'wand' },
  // ── SmartRecruiters ───────────────────────────────────────────────────────
  { name: 'Collabera', ats: 'smartrecruiters', slug: 'Collabera2' },
]
