-- Scoring configuration — editable from the web UI
-- Stores keyword groups, seniority filters, blocklists, etc. as JSONB

CREATE TABLE IF NOT EXISTS scoring_config (
  key TEXT PRIMARY KEY,
  value JSONB NOT NULL,
  updated_at TIMESTAMPTZ DEFAULT now()
);

-- Seed with current hardcoded values

INSERT INTO scoring_config (key, value) VALUES
  ('keyword_groups', '[
    {"name":"b2b_domain","weight":5,"terms":["B2B","B2C","B2B2C","enterprise","SaaS","marketplace","ecommerce","e-commerce","fintech","healthtech","edtech","media","editorial","content-driven","digital ecosystem","developer tools","internal tools","admin tools","CRM","CMS","dashboard","data visualization","reporting","analytics","workflow automation","collaboration tools","productivity tools","platform ecosystem","multi-product platform","complex systems","API","HR technology","talent platform","agreement management","contract management","customer platform","go-to-market","GTM","contact center","financial services","fraud","risk","mobile app","web application","native app","progressive web app","iOS","Android","omnichannel","onboarding","user onboarding","engagement","retention","growth","conversion","revenue","business impact"]},
    {"name":"ai_emerging","weight":4,"terms":["AI-powered","AI-first","agentic AI","AI agents","conversational UI","conversational design","chatbot","voice","voice UI","LLM","generative AI","gen AI","AI-assisted design","AI-assisted","machine learning","probabilistic systems","AI concierge","digital twin","RAG","retrieval-augmented generation","human-in-the-loop","AI design patterns","MCP","prompt engineering","natural language","personalization","recommendation"]},
    {"name":"core_design","weight":3,"terms":["product designer","product design","UX designer","UX design","UI design","UI designer","interaction design","visual design","service design","content design","UX writing","UX copy","motion design","motion graphics","brand design","user experience","user interface","UX principles","UX","end-to-end design","user-centered","human-centered","user flows","wireframes","wireframing","prototyping","prototype","high-fidelity","low-fidelity","mockups","information architecture","IA","responsive design","responsive","cross-platform","multi-platform","pixel-perfect","attention to detail","detail-oriented","design system","design systems","component library","pattern library","design language","style guide","design tokens","atomic design","component-based","scalable design","design patterns","accessibility","accessible design","WCAG","a11y","ADA compliance","inclusive design","universal design","typography","color theory","iconography","illustration","microinteractions","empty state","edge cases","error state","dark mode","localization","internationalization","progressive disclosure","craft","polish","intuitive","seamless","delightful"]},
    {"name":"methods","weight":2,"terms":["user research","usability testing","user testing","user interviews","stakeholder interviews","A/B testing","multivariate testing","experimentation","heuristic evaluation","competitive analysis","competitive audit","card sorting","tree testing","task analysis","journey mapping","customer journey","experience mapping","persona","personas","empathy mapping","contextual inquiry","survey","diary studies","moderated testing","unmoderated testing","remote testing","quantitative research","qualitative research","heatmap","click tracking","behavioral analytics","design thinking","user-centered design","human-centered design","lean UX","design sprint","double diamond","jobs to be done","JTBD","hypothesis-driven","rapid prototyping","rapid iteration","iterative","iteration","continuous iteration","test-and-learn","continuous discovery","product discovery","storyboards","storyboarding","co-design","participatory design","Agile","Scrum","Kanban","sprint","sprint planning","OKRs","KPIs","north star metric","MVP","minimum viable product","design critique","design review","design decisions","design handoff","developer handoff","design QA","DesignOps","ResearchOps","data-driven","data-informed","metrics-driven","funnel analysis","conversion optimization","conversion rate","NPS","CSAT","task success rate","scalable design patterns","0-to-1","zero to one"]},
    {"name":"soft_skills","weight":2,"terms":["cross-functional collaboration","cross-functional","collaboration","partner closely","work closely","stakeholder management","stakeholder communication","stakeholder alignment","influencing without authority","storytelling","presentation skills","communication skills","design rationale","communicate reasoning","workshop facilitation","facilitation","remote collaboration","mentorship","coaching","design leadership","design culture","thought leadership","navigate ambiguity","ambiguity","complex problems","problem solving","creative problem solving","critical thinking","strategic product thinking","strategic thinking","strategic","systems thinking","growth mindset","continuous learning","curiosity","curious","proactive","self-starter","self-directed","autonomous","adaptability","flexibility","resilience","fast-paced","fast-paced environment","business goals","business outcomes","user needs","balance user needs","user advocacy","feedback","design feedback","seek feedback","portfolio","craft"]},
    {"name":"tools","weight":1,"terms":["Figma","FigJam","Sketch","Adobe XD","Adobe Creative Cloud","Adobe Photoshop","Adobe Illustrator","Adobe After Effects","Framer","Principle","ProtoPie","InVision","Axure","Balsamiq","Zeplin","Storybook","Webflow","Maze","UserTesting","Hotjar","FullStory","Amplitude","Mixpanel","Google Analytics","web analytics","Heap","Dovetail","Lookback","Optimal Workshop","Sprig","Pendo","LogRocket","Qualtrics","Miro","Mural","Notion","Confluence","Airtable","Jira","Asana","Trello","Linear","Slack","HTML","CSS","JavaScript","React","Swift","SwiftUI","Git","GitHub","VS Code","Cursor","Claude Code","frontend development","design-to-code","Phenom","Workday","ServiceNow","Salesforce"]}
  ]'::jsonb),
  ('seniority_exclude', '["staff","principal","director","vp","vice president","head of","manager"]'::jsonb),
  ('seniority_newgrad', '["new grad","early career","2026","associate","junior","entry.?level","university","recent graduate","graduate"]'::jsonb),
  ('non_design_titles', '["lead","intern","internship","scholarship","researcher","strategist","motion designer","content designer","graphic designer","interior designer","multimedia designer","packaging designer","engineer","ai trainer","job trends","salaries","data scientist","business analyst","client associate","product specialist","professor","nurse","licensed practical nurse","founder.s office","growth marketing","creative producer","model kit"]'::jsonb),
  ('blocked_companies', '["lensa","itjobswatch"]'::jsonb),
  ('blocked_locations', '["UK","United Kingdom","England","Scotland","Wales","Ireland","Canada","Australia","New Zealand","Germany","France","Spain","Italy","Netherlands","Sweden","Norway","Denmark","Finland","Switzerland","Austria","Belgium","Poland","Portugal","Czech","Romania","Hungary","Singapore","Japan","South Korea","Korea","China","Hong Kong","India","Brazil","Mexico","Argentina","Colombia","Chile","Israel","UAE","Dubai","Qatar","Saudi Arabia","South Africa","Nigeria","Kenya","Amsterdam","Berlin","Munich","Hamburg","London","Manchester","Edinburgh","Dublin","Paris","Lyon","Madrid","Barcelona","Rome","Milan","Stockholm","Gothenburg","Oslo","Copenhagen","Helsinki","Zurich","Geneva","Vienna","Brussels","Warsaw","Prague","Budapest","Toronto","Vancouver","Montreal","Calgary","Sydney","Melbourne","Brisbane","Auckland","Tel Aviv","Bangalore","Mumbai","Delhi","Hyderabad","Chennai","São Paulo","Rio de Janeiro","Mexico City","Buenos Aires","Bogotá","Santiago"]'::jsonb),
  ('job_board_hosts', '["linkedin.com","greenhouse.io","lever.co","ashbyhq.com","myworkdayjobs.com","workday.com","smartrecruiters.com","icims.com","taleo.net","bamboohr.com","jobvite.com","workable.com","wellfound.com","dover.com","rippling.com","recruitee.com","hiring.cafe"]'::jsonb)
ON CONFLICT (key) DO NOTHING;
